build:
	g++ -g egyptian_fractions.cpp -o egyptian_fractions
	g++ -g nth_catalan_number.cpp -o nth_catalan_number
	g++ -g floor_array.cpp -o floor_array
	g++ -g word_break.cpp -o word_break

clean:
	rm egyptian_fractions nth_catalan_number floor_array word_break
