SRC = $(wildcard ./src/*.java)

build:
	javac $(SRC)

RUN = java -classpath src/

run-p1:
	$(RUN) Poduri

run-p2:
	$(RUN) Adrese

run-p3:
	$(RUN) Lego

run-p4:
	$(RUN) Ridge

run-p5:
	$(RUN) Trigigel

COMPILED = $(wildcard ./src/*.class)

clean:
	rm -f $(COMPILED)
